### ISSUE TITLE
Build issues with SMAC import

### ISSUE THREAD

**Issue by Krenair** [Azelphur-Servers/TF2#6]
Traceback (most recent call last):
  File "./build.py", line 90, in <module>
    os.path.join('build/addons/sourcemod/', folder, t)
  File "/usr/lib/python2.7/shutil.py", line 119, in copy
    copyfile(src, dst)
  File "/usr/lib/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 21] Is a directory: 'sourcemod_plugins/SMAC/translations/da'

**Comment by Azelphur** [comment]
Bug fixed in fd45db2 and SMAC added in 155a1c6
